postgresql:
  postgresqlPassword: "VMware1!"
artifactory:
  image:
    registry: releases-docker.jfrog.io
    repository: jfrog/artifactory-oss
  admin:
    password: "VMware1!"
  configMapName: artifactory-oss-bootstrap-config
nginx:
  enabled: false
ingress:
  enabled: true
  defaultBackend:
    enabled: false
  hosts:
  - artifactory.tools.pez.aws.grogscave.net
  annotations:
    kubernetes.io/ingress.class: contour
  service:
    type: ClusterIP
  tls:
    - hosts:
      - artifactory.tools.pez.aws.grogscave.net
      secretName: eduk8s/eduk8s-cert-tls
